#!/usr/bin/env bash

die () {
	echo >&2 "$@"
	exit 1
}

[ "$#" -eq 1 ] || die "Branch name is required"

echo "Creating new branch under the name $1"

git checkout -b $1
git push --set-upstream origin $1
