#!/usr/bin/env bash

die () {
	echo >&2 "$@"
	exit 1
}

[ "$#" -eq 1 ] || die "Branch name is required"

echo "Finding folders with branch $1"

for DIR_NAME in $(find . -type d -maxdepth 1 | grep -v '^.$'); do
	cd $DIR_NAME

  if [ $(git branch -r | grep $1 | wc -l) -ne 0 ]
  then
    echo $DIR_NAME
  fi

	cd ..
done